language: go
os: linux
dist: focal # Use Ubuntu 20.04

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - stable

addons:
  apt:
    packages:
    - attr

script:
  - go get -d -t -v ./...
  - make
  - make test
